### PR TITLE
Added support for payment slips, notification and return urls and payment methods selection

### PR DESCRIPTION
**Pull request by oznek**
- Payment slip setup (aka boleto)
- Notification and return URLs attributes added to instruction
- Payment method configuration
- A validator module for common validation methods

### CODE REVIEW

**Comment by volmer** [comment]
Nice work! Could you please update the `README` with some instructions about how to use your changes?

**Comment by oznek** [comment]
Sure!

**Comment by volmer** [comment]
Right. Please notify us by adding a comment here when you push your changes in the `README`. Thanks! :smiley:

**Comment by Irio** [comment]
This feature comes in a great time, it's a pleasure to merge it, @oznek!

Fill some instructions in the README if you can and I'll release a new version.

**Comment by oznek** [comment]
Documentation done! :)
Please check and tell me if you need more information or clarification!

**Comment by volmer** [comment]
Awesome! :shipit:

**Comment by Irio** [comment]
Well done. Merged.

**Pull request merged**
